apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: dark-latency-check
  namespace: dark
spec:
  metrics:
  - name: p95-latency
    interval: 30s
    count: 3
    successCondition: len(result) > 0 && result[0] < 2
    failureCondition: len(result) == 0 || result[0] >= 2
    provider:
      prometheus:
        address: http://kube-prom-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile(
            0.95,
            sum by (le) (
              rate(loan_decision_latency_seconds_bucket{namespace="dark", service=~"dark-feature-(stable|canary)"}[1m])
            )
          )
