apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dark-feature-dr
  namespace: dark
spec:
  host: dark-feature.dark.svc.cluster.local
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dark-feature-vs
  namespace: dark
spec:
  hosts:
  - dark-feature.dark.svc.cluster.local
  http:
  - name: http
    route:
    - destination:
        host: dark-feature.dark.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: dark-feature.dark.svc.cluster.local
        subset: canary
      weight: 0
